---
# Broken bundler on travis CI - https://github.com/bundler/bundler/issues/2784
before_install:
  - gem update --system 2.1.11
  - gem --version
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.0
  - jruby-19mode
  - rbx-2.1.1
